<?php
// @codingStandardsIgnoreFile
use Likemusic\SaveSize\Block\SavedSizeAttribute as SavedSizeAttributeBlock;
use Likemusic\SaveSize\ViewModel\SavedSizeAttribute as SavedSizeAttributeViewModel;

/** @var SavedSizeAttributeBlock $block */

/** @var SavedSizeAttributeViewModel $viewModel */
$viewModel = $block->getViewModel();
?>
<script>
    window.Likemusic_SaveSize = {
        savedSizeAttribute: <?= /* @escapeNotVerified */ $viewModel->getAsJson() ?>
    }
</script>
