<?php
// @codingStandardsIgnoreFile
use Likemusic\SaveSize\Block\SavedSizeAttribute as SavedSizeAttributeBlock;
use Likemusic\SaveSize\ViewModel\SavedSizeAttribute as SavedSizeAttributeViewModel;

/** @var SavedSizeAttributeBlock $block */

/** @var SavedSizeAttributeViewModel $viewModel */
$viewModel = $block->getViewModel();
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        }
    }
</script>
